export const SEED_TASKS = [
  {
    id: 'C1', slug: 'C1-observability',
    title: 'Engine Observability Pass', status: 'todo', priority: 'high',
    owner: 'codex', issue: 2,
    goal: 'Make every engine decision visible and explainable.',
    definitionOfDone: 'Structured logs for all engine decisions. No silent transitions.',
    acceptanceCriteria: 'Events emitted from all engines. Activity feed displays messages.',
    notes: 'Wire in: DEPENDENCY_UNMET, TRIGGER_FIRED, SYNC_FAILED',
    sourcePath: 'seed',
  },
  {
    id: 'C2', slug: 'C2-transition-guards',
    title: 'State Transition Guardrails', status: 'todo', priority: 'high',
    owner: 'codex', issue: 3,
    goal: 'Enforce valid and auditable state transitions.',
    definitionOfDone: 'Invalid transitions blocked. Manual overrides logged.',
    acceptanceCriteria: 'Invalid transitions rejected. Overrides logged. Restore maintains integrity.',
    notes: null, sourcePath: 'seed',
  },
  {
    id: 'C3', slug: 'C3-seed-realism',
    title: 'Seed/Data Realism Upgrade', status: 'todo', priority: 'high',
    owner: 'codex', issue: 1,
    goal: 'Provide realistic operational scenarios.',
    definitionOfDone: 'Includes happy path, blocked dependency, trigger activation, manual override, archive/restore.',
    acceptanceCriteria: 'Each scenario represented. Clean naming. Docs updated.',
    notes: null, sourcePath: 'seed',
  },
  {
    id: 'C4', slug: 'C4-search-filter',
    title: 'Filters/Search Quality Pass', status: 'todo', priority: 'high',
    owner: 'codex', issue: 4,
    goal: 'Improve board usability.',
    definitionOfDone: 'Multi-field search, composable filters, stable sorting, clear empty states.',
    acceptanceCriteria: 'Search covers IDs, titles, tags, dependencies. Filters combine correctly.',
    notes: null, sourcePath: 'seed',
  },
  {
    id: 'C5', slug: 'C5-sync-hardening',
    title: 'Supabase Sync Hardening', status: 'todo', priority: 'high',
    owner: 'codex', issue: 5,
    goal: 'Make persistence reliable.',
    definitionOfDone: 'Local-first preserved. Failures visible. Retry logic exists.',
    acceptanceCriteria: 'Sync failures handled safely. Status visible. No data loss risk.',
    notes: null, sourcePath: 'seed',
  },
]
